create table if not exists public.rsvp_guests (
  id bigint generated by default as identity primary key,
  invitation_id text not null,
  titular text not null,
  nome text not null,
  normalized_name text not null,
  permite_criancas boolean not null default false,
  observacoes text,
  created_at timestamptz not null default now()
);

create index if not exists rsvp_guests_normalized_name_idx
  on public.rsvp_guests (normalized_name);

create index if not exists rsvp_guests_invitation_id_idx
  on public.rsvp_guests (invitation_id);

create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  invitation_id text not null,
  guest_name text not null,
  status text not null check (status in ('confirmado', 'nao-vai')),
  responded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (invitation_id, guest_name)
);

insert into public.rsvp_guests
  (invitation_id, titular, nome, normalized_name, permite_criancas)
values
  ('convite-001', 'João Silva', 'João Silva', 'joao silva', false),
  ('convite-001', 'João Silva', 'Maria Silva', 'maria silva', false),
  ('convite-002', 'Ana Souza', 'Ana Souza', 'ana souza', false),
  ('convite-003', 'Carlos Andrade', 'Carlos Andrade', 'carlos andrade', false),
  ('convite-003', 'Carlos Andrade', 'Bianca Andrade', 'bianca andrade', false)
on conflict do nothing;
